version: '0.1'
 
services:
  springboot-app:
    image: products_image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products_image_container
    depends_on:
      - mysql
    ports:
      - "8080:8087"
    networks:
      - products_net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://revshop_db:3306/revshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  
  mysql:
    image: mysql:latest
    container_name: revshop_db
    ports:
      - "3304:3306"
    networks:
      - products_net
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE: revshop
    volumes:
      - revshop_vol:/var/lib/mysql
      
networks:
  products_net:
  
volumes:
  revshop_vol: